revise ncclimo calls
E3SM-Project/zppy pull request #228
Opened 2022-03-23 20:38 UTC by chengzhuzhang

This PR closes #220 #165 
@czender Would you please help review this PR. 
In the metadata of newly generated land variable data, there is a new line in `history`: ncap2 -O -s area*=6.37122e6^2/1.0e6;area@long_name=\"Gridcell area\";area@units=\"km^2\" output/LAISUN_000101_002512.nc output/LAISUN_000101_002512.nc

Does this mean the sgs method is applied successful?

A separate question for e3sm2cmip. It's tricky to identify if sgs_frac is applied in cmorized time series. The early versions of land data has following in the global attribute: "
```
:ncclimo_generation_command = "ncclimo --var=${var} -7 --dfl_lvl=1 --no_cll_msr --no_frm_trm --no_stg_grd --yr_srt=1 --yr_end=500 --ypf=25 --map=map_ne30np4_to_cmip6_180x360_aave.20181001.nc " ;
:ncclimo_version = "4.8.1-alpha04""
```
But for newly cmorized data, there is no such history retained...and perhaps we can use one of the temperature variable (i.g. soil temperature) and it's temperature range as an indicator if sgs is applied?

2022-03-23 21:06 UTC, czender requested changes
According to this change what are the possible arguments that will be passed to the `--prc_typ` option? Valid arguments are described here http://nco.sf.net/nco.html#prc_typ.

The --thr=1 option was added to accomodate HR climos on Cori 96 GB nodes, IIRC, because that is the least amount of RAM on any major system. Otherwise thr_nbr will default to 2. This PR should be tested with HR data on Cori before this change is made. 

The additional ncap2 command in the history attribute is because you changed to `-P elm`. As I tried to explain earlier, this causes the regridder to try to produce an output indistinguishable (except for the grid) from native ELM output. And this means rescaling the area field back to ELM-native km2 instead of steradians. Personally I prefer area in steradians, which is the CMIP standard unit for area. Use `'-P sgs' `or `'--sgs_frc=landfrac' instead of `-P elm` to retain the area in steradians. Please decide which form to use based on the stakeholders involved.

2022-03-23 21:15 UTC, czender commented
Regarding your second question, on `e3sm2cmip`, the quoted ncclimo command indicates that SGS regridding was not performed. With newly cmorized data where the command provenance (`history` attribute) has been stripped off/down, then yes, examination of a temperature variable is a perfectly good way to discern whether SGS algorithms were employed. In fact the temperature method is the better method than the `history` attribute because there are corner cases one can imagine where someone might have built a map-file that accounts for SGS regridding and renamed it to the same name as a mapfile that does not account for SGS regridding and then the `history` attribute would give the wrong impression. The proof is always in the temperature field.

2022-03-23 22:28 UTC, chengzhuzhang commented
Thank you!
> According to this change what are the possible arguments that will be passed to the `--prc_typ` option? Valid arguments are described here http://nco.sf.net/nco.html#prc_typ.
> 
Possible input arguments I have seen include, `elm`, `clm2`, `eam`, `cam`. 

> The --thr=1 option was added to accomodate HR climos on Cori 96 GB nodes, IIRC, because that is the least amount of RAM on any major system. Otherwise thr_nbr will default to 2. This PR should be tested with HR data on Cori before this change is made.
> 
I assumed that the high res configuration has a customized setting for all jobs, but it looks [mpas-a] has it but the [ts] [climo] settings were not included yet, I will keep the --thr=1 as a general setting for now.

> The additional ncap2 command in the history attribute is because you changed to `-P elm`. As I tried to explain earlier, this causes the regridder to try to produce an output indistinguishable (except for the grid) from native ELM output. And this means rescaling the area field back to ELM-native km2 instead of steradians. Personally I prefer area in steradians, which is the CMIP standard unit for area. Use `'-P sgs' `or `'--sgs_frc=landfrac' instead of `-P elm` to retain the area in steradians. Please decide which form to use based on the stakeholders involved.

I think it makes sense to use the CMIP standard unit for area to make our data streams consistent, in terms of implementation. In the new commit,
if input is neither `eam` or `cam`, i set  `-P sgs`. Please review again...

2022-03-23 22:44 UTC, czender approved these changes
Changes look good to me.

2022-03-23 22:46 UTC, merged

2022-03-23 23:22 UTC, czender commented
FYI `prc_typ` is coded to recognize model names not versions, so `clm` is recognized and `clm2` is not. The workaround for `clm2` is `-P elm --mdl_nm=clm2`, i.e., the model name as it appears in the filename string for history files is copied from the `prc_typ` argument unless `mdl_nm` is explicitly specified. Also `prc_typ=eam` or `cam` are recognized though they are currently no-ops, i.e., hooks for if/when we need to add some special processing for EAM in the future. The defaults for each processing type are, of course, open for debate and change.

2022-03-23 23:35 UTC, chengzhuzhang commented
Okay, got it, I noticed `clm` in the doc in the list of possible arguments of `prc_typ`. So the implemented logic to use `sgs` if not `eam or `cam` should take account of this variation.

2022-03-24 17:53 UTC, chengzhuzhang commented
Thank you for also testing!
My tests went okay. I think it is just a formatting issue, but good to fix.

2022-03-24 18:07 UTC, chengzhuzhang commented
I will fix this in the ilamb PR

2022-03-24 23:28 UTC, chengzhuzhang commented
This commit https://github.com/E3SM-Project/zppy/pull/197/commits/2425aa6560e0944346b98d01fe05b23c0495d981 should resolve the formatting problem.

2022-03-25 01:18 UTC, czender commented
FYI while adding the spot-check for SGS invocation of ELM files into the regridder, I discovered that a bug related to this PR had crept into the `ncremap` used in E3SMU 1.6.0. The effect of the bug is to essentially ignore the `-P elm` (and similar) options. I am still investigating the dimensions of the problem and will update this tomorrow. However, it seems likely that the minimal workaround will involve changing this PR. Worst case is we may need to issue an "emergency" update E3SMU 1.6.0.1 or somesuch. Fingers crossed that's not necessary.

2022-03-25 03:05 UTC, chengzhuzhang commented
Thank you for updating. I think this PR will most likely be used in operation with the next E3SMU major release. Hope a minimal workaround fix will work..

2022-03-25 18:34 UTC, czender commented
The current E3SMU (1.6.0) will produce incorrect results when SGS regridding is invoked by calling `ncclimo` (or `ncremap`) with the `-P prc_typ` option alone. I intended that option to be sufficient by itself, but a bug I introduced in `ncremap` prevents that option from being fully parsed. As a result, the `-P prc_typ` does not currently trigger SGS regridding. However, it is harmless to leave it in any EZ commands that use it, and it remains essential in processing MPAS data, and it should be retained in those commands because all this will work as intended as of the NCO (5.0.7, which I am now finalizing) and eventually the next E3SMU. 
The workaround to obtain proper SGS normalization with NCO 5.0.6 and E3SMU 1.6.0 is to explicitly invoke `ncclimo` (or `ncremap`) with the `--sgs_frc=landfrac` (for ELM/CLM) or `--sgs_frc=timeMonthly_avg_iceAreaCell` (for MPASSI) options in addition to any `-P prc_typ` options already employed. To be clear, this workaround only need be applied to processing of ELM (not EAM) and MPASSI output. @chengzhuzhang and @xylar would you please confirm receipt/understanding of this issue. I'm happy to answer any questions or help with any PRs necessary to implement this workaround. My apologies for finding a bug on a Friday in the first place!

2022-03-25 19:18 UTC, czender commented
Good question. To generate+regrid ELM timeseries with area in steradians, use `--sgs_frc=landfrac` with or without (it doesn't matter) `-P sgs`. To generate+regrid ELM climos with area in steradians, do the same as for timeseries and, in addition, add `--mdl_nm=elm` or `--mdl_nm=clm2` depending on the string used in the filenames.